### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by parthopdas** [digitalpalitools/web-ui#12]
### goals
- v bdhrs upload translations files to github and localized strings show up with \*\*0\*\*  ongoing development work.

- translation stores
  - web-ui repo: public/locales/...
  - inflection-generator repo: declensions & conjugations.xlxs -> abbreviations text

### stage 0: decouple development work from v bdhrs' uploading process
- [x] in i18n.ts en/translations.json -> translations.en.json (this just puts all files in the same directory, after this v bdhrs can simply upload files into this folder)
  - test: the give giveFeedback button should continue to be localized in all languages
- [x] add 1 column each for all supported locales into the abbreviations table in the inflections.db (these will be empty now, but will light up when v bdhrs add them)

### stage 1: testability => enable us to see what portions are still unlocalized 
- [x] enable psuedoloc locale (ID is 'xx')
  - settable only using devtools console i.e. localStorage.currentScript = 'xx'
  - shows up and english in the drop down
  - there will be a corresponding translations.xx.json file
  - each string here will be same as .en except with ^ appended and $ prepended
- [x] calls to pls will take in a lcid parameter
  - test with lcid = xx for now, actual string will be '^' + en string + '$' (e.g. opt => ^opt$)
  - the en string is taken from from 'name' column of abbreviations table

### stage 2: make it work for en
- [x] pull out all strings from the UI just like 'giveFeedback'
  - naming conventions is 'controlName.shortId'
- [x] pls: test will lcid = en, the values will be taken from 'name' column of abbreviations table
  - test: the tables should now show abbreviations all throughtout
- [x] test the above is complete by setting to psuedoloc locale

### stage 3: integration testing
- [x] web-ui: have v bdhrs provide with an translated strings say translations.si.json 
  - test 1: no work should be needed from your side
  - test 2: web-ui is localized to si
  - test 3: for strings not localized / not present in the translations.si.json, fallback value is from translations.en.json 
- [x] pls: have v bdhrs add at least 1 other column to abbreviations table say si
  - test 1: no work should be needed from your side
  - test 2: ensure tables show up with those string 

### stage 4: other strings in PLS
- [ ] the file that is downloaded with the selected node names 
- [ ] the pattern (eti pr) in summary
- [ ] the word 'like' in summary
- [ ] feedback link
- [ ] pron_type in pron_x types

**Comment by parthopdas** [comment]
@smkvr98 v @bdhrs what else is pending here?

if nothing, lets close this issue.

**Comment by parthopdas** [comment]
closing this as tracking pending issues through other items - please reactivate if necessary.
